### ISSUE TITLE
The model service doesn't update after adding an argument

### ISSUE THREAD

**Issue by yaocw2020** [llmos-ai/llmos#20]
I encounter the problem https://github.com/vllm-project/vllm/pull/1901 during deploying the Qwen model.

Add the argument `--dtype="half"`  to fix it, but the model service doesn't update automatically.

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/9d99dbc5-bbbd-41be-a040-3cf48a53a77b">

**Comment by llmos-ai-alex** [comment]
Close and verified wtih `v0.2.0-rc5`.

#### Verification steps:
1. create a new model with an invalid configuration, e.g., args with `--dtype=half-error`
2. click to modify the config with correct input e.g., `--dtype=half` and waiting for the model service to become ready.
3. model is up and running correctly with the input.

<img width="1592" alt="image" src="https://github.com/user-attachments/assets/23d8effa-08dd-45fa-a273-278e2cb982d3" />
