### ISSUE TITLE
[ENHANCEMENT] Add installation enhancement for cn user behind the GFW

### ISSUE THREAD

**Issue by guangbochen** [llmos-ai/llmos#26]
**Is your enhancement related to a problem? Please describe.**
Add installation enhancement for cn user behind the GFW.

**Describe the solution you'd like**
- Mirror the image to the local image registry, e.g., ACG
- Update installation option e.g., with --locale cn

**Describe alternatives you've considered**

**Additional context**

**Comment by llmos-ai-alex** [comment]
### Verification Steps:
#### Case 1. Install the LLMOS using the `cn` mirror registry:
  - Run`curl -sfL https://get-llmos.1block.ai | INSTALL_LLMOS_VERSION=v0.2.0-rc1 sh -s - --mirror cn`
  - Check the installation logs with `journalctl -u llmos | grep 'llmos-ai-cn-beijing.cr.volces.com/llmos-ai/system-installer-llmos-operator'` which is using the mirror image and the installation should works correctly.

#### Case 2. Set globalSystemRegistry config via `/etc/llmos/config.yaml` file
  ```
mkdir -p /etc/llmos
cat > /etc/llmos/config.yaml << EOF
role: cluster-init
chartRepo: rc
globalSystemImageRegistry: llmos-ai-cn-beijing.cr.volces.com
mirror: cn
EOF
  ```
  - Bootstrap the llmos `curl -sfL https://get-llmos.1block.ai | INSTALL_LLMOS_VERSION=v0.2.0-rc1 sh -s -`
  - Verify that the globalImageRegistry is set to `llmos-ai-cn-beijing.cr.volces.com` on both `/var/lib/llmos/bootstrapmanifests/llmos-prepost.yaml` and `/var/lib/llmos/charts/llmos-operator-config.yaml` config files.
