### ISSUE TITLE
[FEATURE] Add llmos monitoring

### ISSUE THREAD

**Issue by guangbochen** [llmos-ai/llmos#28]
**Is your enhancement related to a problem? Please describe.**

Add LLMOS monitoring that allows users to view the following metrics:
- Cluster, Cluster GPUs metrics.
- Node, Node GPUs metrics.
- ML Workloads e.g., ML cluster, notebook, model service metrics.
- LLM model token metrics.

**Describe the solution you'd like**
- Admin users can enable/disable cluster monitoring and view all monitoring metrics.
- Normal users can view workload metrics after granting monitoring permission to the normal users.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by llmos-ai-alex** [comment]
Verified and passed with `v0.2.0-rc5`.

#### Verification steps:
1. Click `Cluster Tools` from the overview page and click to enable the `limos-monitoring`
2. Using default configurations and enable persistent storage for the Prometheus
  <img width="1582" alt="image" src="https://github.com/user-attachments/assets/cec3ccdc-4e88-449d-9b48-749ee884ac57" />
3. Enable the monitoring and waiting for all of the components to become ready.
4. Ensure the monitoring menu is showing correctly.
  <img width="1854" alt="image" src="https://github.com/user-attachments/assets/ae861533-8c43-4847-b7d5-3afe035ea6fc" />

#### Overview metrics
- [x] Both cluster metrics & GPU metrics are showing the metrics correctly.
<img width="1681" alt="image" src="https://github.com/user-attachments/assets/2190c1a2-4741-4a90-a9f5-9914d3a076be" />

#### Node metrics
- [x] All nodes should have the basic metrics
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/d1b5890c-72c4-48dd-a5e6-5718d1d4f6a4" />

- [x] GPU nodes should contains the GPU metrics
<img width="1573" alt="image" src="https://github.com/user-attachments/assets/c407807b-c7b3-4b29-98fa-fe8d49d3dfca" />


#### Model Service metrics
- [x] model service should contains the token metrics.
<img width="1611" alt="image" src="https://github.com/user-attachments/assets/98b79519-a304-4367-a4ad-82c38f7cd8a4" />

- [x] model service should contains the general metrics.
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/d7196fa0-c35d-4ce0-9b5e-630808260941" />

#### Notebook metrics
- [x] nodebook should contains the general metrics
<img width="1606" alt="image" src="https://github.com/user-attachments/assets/f8e09b26-d6ce-42d8-ac1d-44e18dac6197" />

#### ML Cluster metrics
- [x] After enabling the ML monitoring > Click `Manage` to go to the ML management page, it should show the metrics correctly on its dashboard.
<img width="1857" alt="image" src="https://github.com/user-attachments/assets/9b8d0471-42b4-459c-a6bd-9a30be16a099" />

- [x] Click `ML cluster > Metrics` and it should contains the basic metrics.
